### ISSUE TITLE
Pollen információkat nem tölti be

### ISSUE THREAD

**Issue by rennewpeter** [amaximus/pollen-hu-card#1]
Leírás alapján beállítva, ennek ellenére Nincsenek Pollenek holott a  https://efop180.antsz.hu/polleninformaciok szerint van.

![1](https://user-images.githubusercontent.com/80619883/121874190-6c472880-cd07-11eb-8d7a-bb940ca288e1.png)
![2](https://user-images.githubusercontent.com/80619883/121874447-a7e1f280-cd07-11eb-9e7f-d66569445e29.png)

**Comment by amaximus** [comment]
A kártya sensor_name paramétere alapból pollen_hu  -t vesz, azaz a sensor.pollen_hu szenzor adatait jelenítené meg.
Nézd meg, hogy mi a neve a pollenes szenzornak (Developer Tools->States) saját konfigurációdban és ha nem ez, akkor a kártya paraméterét állítsd annak megfelelően (pl. sensor.my_pollen esetén a kártya sensor_name paraméterét my_pollen  -re kell állítani:
```
type: custom:pollen-hu-card
above_level: 0
title: Pollenek
no_pollen_label: Nincsenek pollenek
sensor_name: my_pollen
```

**Comment by rennewpeter** [comment]
Szia

Köszi a gyors választ. Nálam nincs pollen sensor a dev toolban.

**Comment by amaximus** [comment]
Pedig anélkül nem működik. A kártya csak meglévő adatokat jelenít meg.

HACS-ben az Integrations alatt keress rá a "Pollen Information Hungary'-re, teleptsd, konfigurálj egy szenzort a leírás [1] szerint majd indtsd újra a HA-t.

[1] https://github.com/amaximus/pollen_hu

**Comment by rennewpeter** [comment]
Szia

Amit linkeltél abban már van sensor config. Én ezt raktam fel https://github.com/amaximus/pollen-hu-card

THX a helpet már működik
