### ISSUE TITLE
Nem mutatja a pollenadatokat a kártya

### ISSUE THREAD

**Issue by tanker11** [amaximus/pollen-hu-card#2]
Hello!

Letöltődik a pollen szenzorba az adat, de a kártya azt mutatja, hogy "No pollens".

**Comment by amaximus** [comment]
Hello,

légy szíves add meg a szenzor ill. kártya konfigját. Valószínűleg név nem-egyezés esete áll fenn. Most éppen parlagfű-szezon van.

**Comment by tanker11** [comment]
Köszönöm a gyors reagálást. A névegyezés alapján újra megnéztem a másik, már lezárt Issue-t (#1) és rájöttem, hogy nem olvastam elég figyelmesen.
A "sensor_name:" értékének a telses szenzor nevet írtam, azaz "sensor.valami"-t, pedig csak a "valami"-t kellett volna. Úgy vettem, mintha entity hivatkozás lenne.

Szóval most megy, és nagyon tetszik, köszönöm!
