### ISSUE TITLE
Csak bizonyos allergének?

### ISSUE THREAD

**Issue by tolnai** [amaximus/pollen-hu-card#6]
Szia, megoldható az jelenleg valahogy, hogy csak 1-2 féle pollent jelezzen ki (feltéve ha jelen van)? Másképp: parlagfűre vagyok allergiás, a többi pollen nem igazán érdekel. Vagy az eredeti szenzorból kellene valahogy egy származtatott másik dedikált szenzort csinálni?

**Comment by amaximus** [comment]
Szia, ez a kártya nem támogat szűrőt. Ellenben [custom button card](https://github.com/custom-cards/button-card)-dal símán megoldható, lévén nagyon rugalmasan használható. Pl. valami ilyesmi:
```
type: custom:button-card
icon: mdi:blur
size: 30px
styles:
  label:
    - font-size: 85%
  card:
    - height: 70px
    - background: transparent
    - box-shadow: none
    - border: 0px
  icon:
   - color: >
       [[[
         var pollens = states['sensor.pollen'].attributes.pollens;
         for (var k=0; k < pollens.length; k++) {
           if ( pollens[k].name == "Parlagfű" ) { 
             if ( pollens[k].value == "3") { return "red"}
             if ( pollens[k].value == "2") { return "orange"}
         }
         return "var(--paper-item-icon-color)";
      ]]]
label: Parlagfű
show_label: true
show_name: false
entity: sensor.pollen
color_type: icon
```

**Comment by tolnai** [comment]
Köszi szépen a gyors választ! Megpróbáltam valahogy egy mushroom kártyába varázsolni ezt a dolgot, de mivel úgy látom ott még jinja-t se lehet írni, nem sikerült. Szóval custom button card lesz belőle, köszi a minta konfigot, így működik!

**Comment by amaximus** [comment]
Közben az új verzió támogatja, hogy csak a konfigurációban felsorolt allergéneket figyelje.
