### ISSUE TITLE
Default sensor name

### ISSUE THREAD

**Issue by lexus440** [amaximus/pollen-hu-card#7]
Just to clarify, default sensor name should be:
`pollen_adatok`
since this is the default sensor name in the integration.

So card settings should look like something like this:

```
type: custom:pollen-hu-card
above_level: 0
title: Aktuális pollenek
sensor_name: pollen_adatok
```

Köszönöm szépen a munkádat!

**Comment by amaximus** [comment]
For some versions now HASS has started to auto-generate names for sensors.
This depends on the language HASS is running on, therefore the default name is varying for different users based on the HASS language they set for their environments.
If you need a sensor name different from what is considered default by the card, please use `sensor_name`.
